export const PRODUCT_CATEGORY = [
    "SELECT THE CATEGORY...",
    "Automobiles",
    "Makeup",
    "Electronics",
    "Clothing",
    "Footwear",
    "Home Appliances",
    "Furniture",
    "Toys",
    "Books",
    "Sports Equipment",
    "Jewelry",
    "Healthcare Products",
    "Groceries",
    "Pet Supplies",
    "Garden Supplies",
    "Music Instruments",
    "Watches",
    "Photography Equipment",
    "Travel Accessories",
    "Stationery",
    "Jersey",
    "Anime Dress"
]